/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Backend.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class ChangeUserName extends javax.swing.JDialog {

    Sistema s;

    public ChangeUserName(java.awt.Frame parent, boolean modal, Sistema s) {
        super(parent, modal);
        initComponents();
        this.s = s;
        this.setTitle("Alterar Nome do Utilizador - " + s.getCurrentUser().getUserName() + " ("+ s.getCurrentUser().getEmail()+")");
        
        tbUserName.setText(s.getCurrentUser().getUserName());
         
        EnableBtnChangeUserData();

        tbUserName.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void changedUpdate(DocumentEvent arg0) {
                EnableBtnChangeUserData();
            }

            @Override
            public void insertUpdate(DocumentEvent arg0) {
                EnableBtnChangeUserData();
            }

            @Override
            public void removeUpdate(DocumentEvent arg0) {
                EnableBtnChangeUserData();
            }

        });
    }

    void EnableBtnChangeUserData() {
        boolean b = true;

        //Check instance od Sistems s
        if (s == null) {
            JOptionPane.showMessageDialog(null, "A variável s não foi instanciada.\nImpossível continuar");
            b = false;
        }

        //Check username cannot be empty
        if (tbUserName.getText().isBlank()) {
            lblInsertNameWarning.setText("Introduza o novo nome");
            b = false;
        } else {
            lblInsertNameWarning.setText("");
        }             
        
        btnChangeUserName.setEnabled(b);

    }//EnableBtnRegisterUser

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tbUserName = new javax.swing.JTextField();
        lblInsertNameWarning = new javax.swing.JLabel();
        btnChangeUserName = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Nome de Utilizador");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 300, 22));

        tbUserName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tbUserName.setForeground(new java.awt.Color(102, 102, 102));
        tbUserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbUserNameActionPerformed(evt);
            }
        });
        getContentPane().add(tbUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 39, 418, 30));

        lblInsertNameWarning.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblInsertNameWarning.setForeground(new java.awt.Color(255, 0, 0));
        lblInsertNameWarning.setText("lblInsertNameWarning");
        getContentPane().add(lblInsertNameWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 75, 300, 20));

        btnChangeUserName.setBackground(new java.awt.Color(51, 110, 123));
        btnChangeUserName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnChangeUserName.setForeground(new java.awt.Color(255, 255, 255));
        btnChangeUserName.setText("Alterar Nome");
        btnChangeUserName.setBorderPainted(false);
        btnChangeUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeUserNameActionPerformed(evt);
            }
        });
        getContentPane().add(btnChangeUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 117, 200, 46));

        btnExit.setBackground(new java.awt.Color(51, 110, 123));
        btnExit.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Sair");
        btnExit.setBorderPainted(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 117, 200, 46));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbUserNameActionPerformed
        EnableBtnChangeUserData();
    }//GEN-LAST:event_tbUserNameActionPerformed

    private void btnChangeUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeUserNameActionPerformed
        s.getUsersRepository().changeUserNameById(s.getCurrentUser().getUserId(), tbUserName.getText());
        JOptionPane.showMessageDialog(null, "O Nome do utilizador foi alterado para "+ tbUserName.getText() +" com sucesso!");
        this.dispose();
    }//GEN-LAST:event_btnChangeUserNameActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeUserName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeUserName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeUserName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeUserName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                /*Registo2 dialog = new Registo2(new javax.swing.JFrame(), true, s);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);*/
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeUserName;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblInsertNameWarning;
    private javax.swing.JTextField tbUserName;
    // End of variables declaration//GEN-END:variables
}
