//https://www.youtube.com/watch?v=F_6lUrruyXA
package Frontend;

import Backend.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VarianInstaller
 */
public class ChangeTaskStatus extends javax.swing.JDialog {

    Sistema s;

    TaskStatus SelectedStatus;
    DefaultTableModel modelTask;
    Integer SelectedTaskId = -1;

    public ChangeTaskStatus(java.awt.Frame parent, boolean modal, Sistema s) {
        super(parent, modal);
        initComponents();
        this.s = s;

        Validacoes.SetDialogProperties(this, s, 800, 580, "Atualizar Estado da Tarefa");

        rbNotStarted.setSelected(false);
        rbInProgress.setSelected(false);
        rbInProgress.setSelected(false);
        SelectedStatus = TaskStatus.NOTSTARTED;

        //-------Tasks table----------------------------------------------------
        //set jtable selection to single row
        tableTasks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        //prevent editing of jtable cells
        tableTasks.setDefaultEditor(Object.class, null);

        //create model to handle columns and rows
        modelTask = new DefaultTableModel();
        modelTask.addColumn("Id da Tarefa");
        modelTask.addColumn("Título da Tarefa");
        modelTask.addColumn("Descrição da Tarefa");
        modelTask.addColumn("Data de Início");
        modelTask.addColumn("Data de Fim");

        //relate model to table
        tableTasks.setModel(modelTask);
        //----------------------------------------------------------------------

        //fill tasks table
        for (Task t : s.getRepositoryTasks().getTasksAssignedToUser(s.getCurrentUser().getUserId())) {
            if (t.getEndDate() == null) {
                modelTask.addRow(new Object[]{
                    t.getTaskId(),
                    t.getTitle(),
                    t.getDescription(),
                    Validacoes.FormatDate(t.getStartDate()),
                    ""
                });
            } else {
                modelTask.addRow(new Object[]{
                    t.getTaskId(),
                    t.getTitle(),
                    t.getDescription(),
                    Validacoes.FormatDate(t.getStartDate()),
                    Validacoes.FormatDate(t.getEndDate())
                });
            }

        }
        EnableBtnUpdateTask();
        //Events----------------------------------------------------------------
        //jtable selection change event

        //jtable selection change event
        tableTasks.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                SelectedTaskId = (int) tableTasks.getValueAt(tableTasks.getSelectedRow(), 0);
                UpdateControls();
                EnableBtnUpdateTask();
            }
        });

    }

    void UpdateControls() {
        if (SelectedTaskId >= 0) {
            Task t = s.getRepositoryTasks().getTaskByTaskId(SelectedTaskId);

            //Select Status
            switch (t.getEnumStatus()) {
                case NOTSTARTED: {
                    rbNotStarted.setSelected(true);
                    SelectedStatus = TaskStatus.NOTSTARTED;
                    break;
                }
                case INPROGRESS: {
                    rbInProgress.setSelected(true);
                    SelectedStatus = TaskStatus.INPROGRESS;
                    break;
                }
                case FINISHED: {
                    rbFinished.setSelected(true);
                    SelectedStatus = TaskStatus.FINISHED;
                    break;
                }
                default: {
                    System.out.println("ERROR: Task Status not definrd");
                    break;
                }
            }
        }
    }

    void EnableBtnUpdateTask() {
        boolean b = true;
        if (tableTasks.getSelectedRow() == -1) {
            lbltableTaskWarning.setText("Selecione uma tarefa");
            b = false;
        } else {
            lbltableTaskWarning.setText("");
        }

        btnCreateTask.setEnabled(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpPriority = new javax.swing.ButtonGroup();
        btngrpStatus = new javax.swing.ButtonGroup();
        btnCreateTask = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableTasks = new javax.swing.JTable();
        lbltableTaskWarning = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        rbNotStarted = new javax.swing.JRadioButton();
        rbInProgress = new javax.swing.JRadioButton();
        rbFinished = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Criar Tarefa");

        btnCreateTask.setBackground(new java.awt.Color(51, 110, 123));
        btnCreateTask.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnCreateTask.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateTask.setText("Atualizar Estado da Tarefa");
        btnCreateTask.setBorder(null);
        btnCreateTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateTaskActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(51, 110, 123));
        btnCancel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancelar");
        btnCancel.setBorder(null);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selecionar Tarefa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 18))); // NOI18N
        jPanel6.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        tableTasks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tableTasks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(tableTasks);

        lbltableTaskWarning.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lbltableTaskWarning.setText("lbltableTaskWarning");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lbltableTaskWarning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltableTaskWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 18))); // NOI18N
        jPanel8.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        btngrpStatus.add(rbNotStarted);
        rbNotStarted.setText("Não Iniciada");

        btngrpStatus.add(rbInProgress);
        rbInProgress.setText("Em Progresso");

        btngrpStatus.add(rbFinished);
        rbFinished.setText("Terminada");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbNotStarted)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbInProgress)
                .addGap(4, 4, 4)
                .addComponent(rbFinished)
                .addContainerGap(490, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbNotStarted)
                    .addComponent(rbInProgress)
                    .addComponent(rbFinished))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(btnCreateTask, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateTask, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*public void addTask(int CreatedBy, String Title, 
    String Description, TaskPriority pt,TaskStatus et,Date DataDeInicio*/
    private void btnCreateTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateTaskActionPerformed

        s.getRepositoryTasks().updateTaskStatusById(SelectedTaskId, SelectedStatus);
        if(SelectedStatus==TaskStatus.FINISHED)
        {
            
        }
        else            
        {
        }
        
    }//GEN-LAST:event_btnCreateTaskActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CriarTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CriarTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CriarTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CriarTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                CriarTarefa dialog = new CriarTarefa(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreateTask;
    private javax.swing.ButtonGroup btngrpPriority;
    private javax.swing.ButtonGroup btngrpStatus;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbltableTaskWarning;
    private javax.swing.JRadioButton rbFinished;
    private javax.swing.JRadioButton rbInProgress;
    private javax.swing.JRadioButton rbNotStarted;
    private javax.swing.JTable tableTasks;
    // End of variables declaration//GEN-END:variables
}
