/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Backend.Sistema;
import Backend.TaskList;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACVL
 */
public class ChangeTaskList extends javax.swing.JDialog {
    Sistema s;
    DefaultTableModel modelTaskList;
    /**
     * Creates new form ChangeTaskList
     */
    public ChangeTaskList(java.awt.Frame parent, boolean modal, Sistema s) {
        super(parent, modal);
        initComponents();
        this.s=s;
        
        //set jtable selection to single row------------------------------------------------------------
        tableTaskList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        //prevent editing of jtable cells
        tableTaskList.setDefaultEditor(Object.class, null);

        //create modelProjectsOwnedByUser to handle columns and rows
        modelTaskList = new DefaultTableModel();
        modelTaskList.addColumn("Id da Task List");
        modelTaskList.addColumn("Título da TaskList");
        modelTaskList.addColumn("Descrição da TaskList");
        tableTaskList.setModel(modelTaskList);

        ArrayList<TaskList> TaskListsbyOwner = new ArrayList<>();

        //Select projects owned by current user (owner of projects)
        //Only owners can create Task Lista and Tasks. See Specification
        TaskListsbyOwner = s.getRepositoryTaskLists().getTaskListsbyOwner(s.getCurrentUser().getUserId());

        //Add rows to table with projects info
        for (TaskList p : TaskListsbyOwner) {
            modelTaskList.addRow(new Object[]{
                p.getTaskListId(),
                p.getTitle(),
                p.getDescription()
            });

        }
        tbTitle.setText("");
        tbDescription.setText("");
        enablebtnUpdate();
        
        //Events
        tableTaskList.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                SelectTaskList();
                 
            }
        });
        //TextBox events
        tbTitle.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void changedUpdate(DocumentEvent arg0) {
                enablebtnUpdate();
            }

            @Override
            public void insertUpdate(DocumentEvent arg0) {
                enablebtnUpdate();
            }

            @Override
            public void removeUpdate(DocumentEvent arg0) {
                enablebtnUpdate();
            }
        });
            
        
            tbDescription.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void changedUpdate(DocumentEvent arg0) {
                enablebtnUpdate();
            }

            @Override
            public void insertUpdate(DocumentEvent arg0) {
                enablebtnUpdate();
            }

            @Override
            public void removeUpdate(DocumentEvent arg0) {
                enablebtnUpdate();
            }
        });
    }
void SelectTaskList (){

    tbTitle.setText((String) tableTaskList.getValueAt(tableTaskList.getSelectedRow() ,1));
    tbDescription.setText((String) tableTaskList.getValueAt(tableTaskList.getSelectedRow() ,2));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelProjectsOwnedByUser = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTaskList = new javax.swing.JTable();
        tbTitle = new javax.swing.JTextField();
        tbDescription = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelProjectsOwnedByUser.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tableTaskList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tableTaskList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tableTaskList);

        javax.swing.GroupLayout panelProjectsOwnedByUserLayout = new javax.swing.GroupLayout(panelProjectsOwnedByUser);
        panelProjectsOwnedByUser.setLayout(panelProjectsOwnedByUserLayout);
        panelProjectsOwnedByUserLayout.setHorizontalGroup(
            panelProjectsOwnedByUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProjectsOwnedByUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelProjectsOwnedByUserLayout.setVerticalGroup(
            panelProjectsOwnedByUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProjectsOwnedByUserLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTitleActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(51, 110, 123));
        btnExit.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Cancelar");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(51, 110, 123));
        btnUpdate.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Guardar");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbTitle)
                    .addComponent(tbDescription)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 401, Short.MAX_VALUE)
                        .addComponent(btnExit)
                        .addGap(34, 34, 34)
                        .addComponent(btnUpdate)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelProjectsOwnedByUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addComponent(tbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(tbDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnUpdate))
                .addGap(22, 22, 22))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addComponent(panelProjectsOwnedByUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(182, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbTitleActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
    int i=(int)tableTaskList.getValueAt(tableTaskList.getSelectedRow() ,0);
    tableTaskList.setValueAt(tbTitle.getText(), tableTaskList.getSelectedRow(), 1);
    tableTaskList.setValueAt(tbDescription.getText(), tableTaskList.getSelectedRow(), 2);
    s.getRepositoryTaskLists().updatebytasklistid(i, tbTitle.getText(), tbDescription.getText());
    JOptionPane.showMessageDialog(null, "A TaskList foi actualizada com sucesso!");
    }//GEN-LAST:event_btnUpdateActionPerformed
void enablebtnUpdate(){
    if (tbTitle.getText().isBlank() || tbDescription.getText().isBlank())
    {
        btnUpdate.setEnabled (false);
    }
    else
    {
        btnUpdate.setEnabled (true);
    }
}
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ChangeTaskList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ChangeTaskList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ChangeTaskList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ChangeTaskList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ChangeTaskList dialog = new ChangeTaskList(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
 //   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelProjectsOwnedByUser;
    private javax.swing.JTable tableTaskList;
    private javax.swing.JTextField tbDescription;
    private javax.swing.JTextField tbTitle;
    // End of variables declaration//GEN-END:variables
}
