/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Backend.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class ChangeUserPassword extends javax.swing.JDialog {

    Sistema s;

    public ChangeUserPassword(java.awt.Frame parent, boolean modal, Sistema s) {
        super(parent, modal);
        initComponents();
        this.s = s;
        this.setTitle("Alterar Password de Utilizador - " + s.getCurrentUser().getUserName() + " (" + s.getCurrentUser().getEmail() + ")");

        tbPassword.setText("");
        tbConfirmPassword.setText("");

        EnableBtnChangeUserData();

        tbCurrentPassword.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void changedUpdate(DocumentEvent arg0) {
                EnableBtnChangeUserData();
            }

            @Override
            public void insertUpdate(DocumentEvent arg0) {
                EnableBtnChangeUserData();
            }

            @Override
            public void removeUpdate(DocumentEvent arg0) {
                EnableBtnChangeUserData();
            }

        });

        tbPassword.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void changedUpdate(DocumentEvent arg0) {
                EnableBtnChangeUserData();
            }

            @Override
            public void insertUpdate(DocumentEvent arg0) {
                EnableBtnChangeUserData();
            }

            @Override
            public void removeUpdate(DocumentEvent arg0) {
                EnableBtnChangeUserData();
            }

        });

        tbConfirmPassword.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void changedUpdate(DocumentEvent arg0) {
                EnableBtnChangeUserData();
            }

            @Override
            public void insertUpdate(DocumentEvent arg0) {
                EnableBtnChangeUserData();
            }

            @Override
            public void removeUpdate(DocumentEvent arg0) {
                EnableBtnChangeUserData();
            }

        });

    }

    void EnableBtnChangeUserData() {
        boolean b = true;

        //Check instance od Sistems s
        if (s == null) {
            JOptionPane.showMessageDialog(null, "A variável s não foi instanciada.\nImpossível continuar");
            b = false;
        }
        //Check Current Password blank ---------------------------------------------
        if (tbCurrentPassword.getText().isBlank() || tbCurrentPassword.getText().length() < 6) {
            lblCurrentPasswordWarning.setText("Introduza a Password Atual");
            b = false;
        } else if (!tbCurrentPassword.getText().equals(s.getCurrentUser().getUserPassword())) {
            lblCurrentPasswordWarning.setText("Password Incorreta");
            b = false;
        } else {
            lblCurrentPasswordWarning.setText("");
        }

        //Check New Password blank ---------------------------------------------
        if (tbPassword.getText().isBlank() || tbPassword.getText().length() < 6) {
            lblInsertPasswordWarning.setText("Introduza uma Password (6 caractéres mínimo)");
            lblInsertPasswordConfirmationWarning.setText("Confirme a Password");
            b = false;
        } else if (tbPassword.getText().length() >= 6 && !tbConfirmPassword.getText().equals(tbPassword.getText())) {
            lblInsertPasswordWarning.setText("");
            lblInsertPasswordConfirmationWarning.setText("Confirme a Password");
            b = false;
        } else {
            lblInsertPasswordWarning.setText("");
            lblInsertPasswordConfirmationWarning.setText("");
        }

        btnChangeUserPassword.setEnabled(b);

    }//EnableBtnRegisterUser

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        tbPassword = new javax.swing.JPasswordField();
        lblInsertPasswordWarning = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tbConfirmPassword = new javax.swing.JPasswordField();
        lblInsertPasswordConfirmationWarning = new javax.swing.JLabel();
        btnChangeUserPassword = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tbCurrentPassword = new javax.swing.JPasswordField();
        lblCurrentPasswordWarning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registo");
        setResizable(false);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Nova Password:");

        tbPassword.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tbPassword.setForeground(new java.awt.Color(102, 102, 102));
        tbPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbPasswordActionPerformed(evt);
            }
        });

        lblInsertPasswordWarning.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblInsertPasswordWarning.setForeground(new java.awt.Color(255, 0, 0));
        lblInsertPasswordWarning.setText("lblInsertPasswordWarning");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Confirmar Password:");

        tbConfirmPassword.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tbConfirmPassword.setForeground(new java.awt.Color(102, 102, 102));
        tbConfirmPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbConfirmPasswordActionPerformed(evt);
            }
        });

        lblInsertPasswordConfirmationWarning.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblInsertPasswordConfirmationWarning.setForeground(new java.awt.Color(255, 0, 0));
        lblInsertPasswordConfirmationWarning.setText("lblInsertPasswordConfirmationWarning");

        btnChangeUserPassword.setBackground(new java.awt.Color(51, 110, 123));
        btnChangeUserPassword.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnChangeUserPassword.setForeground(new java.awt.Color(255, 255, 255));
        btnChangeUserPassword.setText("Alterar Password");
        btnChangeUserPassword.setBorderPainted(false);
        btnChangeUserPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeUserPasswordActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(51, 110, 123));
        btnExit.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Sair");
        btnExit.setBorderPainted(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Password Atual:");

        tbCurrentPassword.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tbCurrentPassword.setForeground(new java.awt.Color(102, 102, 102));
        tbCurrentPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbCurrentPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbCurrentPasswordActionPerformed(evt);
            }
        });

        lblCurrentPasswordWarning.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblCurrentPasswordWarning.setForeground(new java.awt.Color(255, 0, 0));
        lblCurrentPasswordWarning.setText("lblCurrentPasswordWarning");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbCurrentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCurrentPasswordWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInsertPasswordWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInsertPasswordConfirmationWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnChangeUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tbCurrentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lblCurrentPasswordWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tbPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lblInsertPasswordWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tbConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lblInsertPasswordConfirmationWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChangeUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeUserPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeUserPasswordActionPerformed
        s.getUsersRepository().changeUserPasswordById(s.getCurrentUser().getUserId(), tbPassword.getText());
        JOptionPane.showMessageDialog(null, "A Password do utilizador foi alterado com sucesso!");
        this.dispose();
    }//GEN-LAST:event_btnChangeUserPasswordActionPerformed

    private void tbPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbPasswordActionPerformed
        EnableBtnChangeUserData();
    }//GEN-LAST:event_tbPasswordActionPerformed

    private void tbConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbConfirmPasswordActionPerformed
        EnableBtnChangeUserData();
    }//GEN-LAST:event_tbConfirmPasswordActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void tbCurrentPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbCurrentPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbCurrentPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeUserPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeUserPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeUserPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeUserPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                /*Registo2 dialog = new Registo2(new javax.swing.JFrame(), true, s);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);*/
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeUserPassword;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblCurrentPasswordWarning;
    private javax.swing.JLabel lblInsertPasswordConfirmationWarning;
    private javax.swing.JLabel lblInsertPasswordWarning;
    private javax.swing.JPasswordField tbConfirmPassword;
    private javax.swing.JPasswordField tbCurrentPassword;
    private javax.swing.JPasswordField tbPassword;
    // End of variables declaration//GEN-END:variables
}
