/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Backend.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VarianInstaller
 */
public class CreateTaskLists extends javax.swing.JDialog {

    Sistema s;

    DefaultTableModel model;

    /**
     * Creates new form CriarListaDeTarefas
     */
    public CreateTaskLists(java.awt.Frame parent, boolean modal, Sistema s) {
        super(parent, modal);
        initComponents();
        this.s = s;
        this.setTitle("Criar Lista de Tarefas - " + s.getCurrentUser().getUserName() + " (" + s.getCurrentUser().getEmail() + ")");
        
        //set jtable selection to single row
        tableProjects.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        
        //prevent editing of jtable cells
        tableProjects.setDefaultEditor(Object.class, null);
        
        //create model to handle columns and rows
        model = new DefaultTableModel();        
        model.addColumn("Id do Projeto");
        model.addColumn("Título do Projeto");
        model.addColumn("Descrição do Projeto");
        model.addColumn("Owner do projeto");
        tableProjects.setModel(model);
        
         
        ArrayList<Project> ProjectsByOwner = new ArrayList<>();
        
        //Select projects owned by current user (owner of projects)
        //Only owners can create Task Lista and Tasks. See Specification
        ProjectsByOwner = s.getRepositoryProjects().getProjectsByOwner(s.getCurrentUser().getUserId());
        
        //Add rows to table with projects info
        for (Project p : ProjectsByOwner) {
            model.addRow(new Object[]{
                p.getProjectId(),
                p.getProjectTitle(),
                p.getProjectDescription()
            });

        }
        EnableBtnCreateTaskList();

        
        //Listeners for events
       
        //TaskList description event
        tbTaskListDescription.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void changedUpdate(DocumentEvent arg0) {
                EnableBtnCreateTaskList();
            }

            @Override
            public void insertUpdate(DocumentEvent arg0) {
                EnableBtnCreateTaskList();
            }

            @Override
            public void removeUpdate(DocumentEvent arg0) {
                EnableBtnCreateTaskList();
            }

        });

        //TaskList Title event
        tbTaskListTitle.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void changedUpdate(DocumentEvent arg0) {
                EnableBtnCreateTaskList();
            }

            @Override
            public void insertUpdate(DocumentEvent arg0) {
                EnableBtnCreateTaskList();
            }

            @Override
            public void removeUpdate(DocumentEvent arg0) {
                EnableBtnCreateTaskList();
            }

        });
        
        //jtable selection change event
        tableProjects.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                EnableBtnCreateTaskList();
                 
            }
        });
    }

    void EnableBtnCreateTaskList() {
        boolean b = true;

        //TaskList Title cannot be null
        if (tbTaskListTitle.getText().isBlank()) {
            lblTitleWarning.setText("Introduza o título da lista de tarefas");
            b = false;
        } else {
            lblTitleWarning.setText("");
        }

        //TaskList description cannot be null
        if (tbTaskListDescription.getText().isBlank()) {
            lblDescriptionWarning.setText("Introduza uma descrição para a lista de tarefas");
            b = false;
        } else {
            lblDescriptionWarning.setText("");
        }

        if (tableProjects.getSelectedRow() == -1) {
            lbltableProjectWarning.setText("Selecione um projeto para associá-lo a esta tarefa");
            b = false;
        } else {
            lbltableProjectWarning.setText("");
        }

        btnCreateTaskList.setEnabled(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancel = new javax.swing.JButton();
        btnCreateTaskList = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProjects = new javax.swing.JTable();
        lbltableProjectWarning = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tbTaskListTitle = new javax.swing.JTextField();
        lblTitleWarning = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tbTaskListDescription = new javax.swing.JTextField();
        lblDescriptionWarning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Criar lista de tarefas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 623, -1, -1));

        btnCreateTaskList.setText("Criar lista de tarefas");
        btnCreateTaskList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateTaskListActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreateTaskList, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 623, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Associar a projeto"));

        tableProjects.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tableProjects.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tableProjects);

        lbltableProjectWarning.setText("lbltableProjectWarning");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbltableProjectWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltableProjectWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 242, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Título da Lista de Tarefas"));

        tbTaskListTitle.setPreferredSize(new java.awt.Dimension(30, 20));

        lblTitleWarning.setText("lblTitleWarning");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbTaskListTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitleWarning, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tbTaskListTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitleWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1032, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Descrição da Lista de Tarefas"));

        lblDescriptionWarning.setText("lblDescriptionWarning");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbTaskListDescription)
                    .addComponent(lblDescriptionWarning, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(tbTaskListDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescriptionWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 1032, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed
 
    private void btnCreateTaskListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateTaskListActionPerformed
    
        //Get ProjectId from tableProjects
        int ProjectId = (Integer)tableProjects.getModel().getValueAt(tableProjects.getSelectedRow(), 0);
        String ProjectTitle = (String)tableProjects.getModel().getValueAt(tableProjects.getSelectedRow(), 1);
        System.out.println("ProjectID: " +ProjectId );
        
         //public void addListaDeTarefa(int ProjectId, String Title, String Description, int CreatedBy ){
        s.getRepositoryTaskLists().addTaskList( ProjectId, tbTaskListTitle.getText(),  tbTaskListDescription.getText(), s.getCurrentUser().getUserId() );
        JOptionPane.showMessageDialog(null, "A lista de tarefas\n" + tbTaskListTitle.getText( )+ 
                "\nfoi criada e associada ao projeto\n" + ProjectTitle + "\ncom sucesso!");
        this.dispose();
    }//GEN-LAST:event_btnCreateTaskListActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CriarListaDeTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CriarListaDeTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CriarListaDeTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CriarListaDeTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                CriarListaDeTarefas dialog = new CriarListaDeTarefas(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreateTaskList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescriptionWarning;
    private javax.swing.JLabel lblTitleWarning;
    private javax.swing.JLabel lbltableProjectWarning;
    private javax.swing.JTable tableProjects;
    private javax.swing.JTextField tbTaskListDescription;
    private javax.swing.JTextField tbTaskListTitle;
    // End of variables declaration//GEN-END:variables
}
