/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Backend.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class CreateProject extends javax.swing.JDialog {

    Sistema s;

    //Constructor
    public CreateProject(java.awt.Frame parent, boolean modal, Sistema s) {
        super(parent, modal);
        initComponents();
        this.s = s;
        Validacoes.SetDialogProperties(this, s, 660, 660, "Criar Projeto");

        EnablebtnCreateproject();

        txtProjectDescription.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void changedUpdate(DocumentEvent arg0) {
                EnablebtnCreateproject();
            }

            @Override
            public void insertUpdate(DocumentEvent arg0) {
                EnablebtnCreateproject();
            }

            @Override
            public void removeUpdate(DocumentEvent arg0) {
                EnablebtnCreateproject();
            }
        });

        txtProjectTitle.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void changedUpdate(DocumentEvent arg0) {
                EnablebtnCreateproject();
            }

            @Override
            public void insertUpdate(DocumentEvent arg0) {
                EnablebtnCreateproject();
            }

            @Override
            public void removeUpdate(DocumentEvent arg0) {
                EnablebtnCreateproject();
            }

        });

        calStartDate.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                EnablebtnCreateproject();
            }
        });

        calEndDate.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                EnablebtnCreateproject();
            }
        });

    } //constructor

    void EnablebtnCreateproject() {
        boolean b = true;

        //Project Title
        if (txtProjectTitle.getText().isBlank()) {
            b = false;
            lblTitleWarning.setText("Introduza um título para o projeto");
        } else {
            lblTitleWarning.setText("");
        }

        //Project description
        if (txtProjectDescription.getText().isBlank()) {
            b = false;
            lblDescriptionWarning.setText("Introduza uma descrição para o projeto");
        } else {
            lblDescriptionWarning.setText("");
        }

        long startdate = 1 + (calStartDate.getDateInMillis() / (1000 * 60 * 60 * 24));

        long enddate = 1 + (calEndDate.getDateInMillis() / (1000 * 60 * 60 * 24));

        long currentdate = System.currentTimeMillis() / (1000 * 60 * 60 * 24);

        if (startdate < currentdate) {
            b = false;
            lblStartDateWarning.setText("Data de início do projeto deve ser igual ou superior à data atual");
        } else {
            lblStartDateWarning.setText("");
        }

        if (enddate < startdate) {

            b = false;
            lblEndDateWarning.setText("Data de fim do projeto deve ser igual ou superior à data de início");
        } else {
            lblEndDateWarning.setText("");
        }

        btnCreateProject.setEnabled(b);
    }//EnablebtnCreateproject

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        btnCancel = new javax.swing.JButton();
        btnCreateProject = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblDescriptionWarning = new javax.swing.JLabel();
        txtProjectDescription = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtProjectTitle = new javax.swing.JTextField();
        lblTitleWarning = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        calStartDate = new org.jdesktop.swingx.JXDatePicker();
        lblStartDateWarning = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        calEndDate = new org.jdesktop.swingx.JXDatePicker();
        lblEndDateWarning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Criar Projeto");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancel.setBackground(new java.awt.Color(51, 110, 123));
        btnCancel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Sair");
        btnCancel.setBorder(null);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 531, 200, 46));

        btnCreateProject.setBackground(new java.awt.Color(51, 110, 123));
        btnCreateProject.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnCreateProject.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateProject.setText("Criar Projeto");
        btnCreateProject.setBorder(null);
        btnCreateProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateProjectActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreateProject, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 200, 46));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descrição", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 18))); // NOI18N
        jPanel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        lblDescriptionWarning.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblDescriptionWarning.setForeground(new java.awt.Color(255, 0, 0));
        lblDescriptionWarning.setText("lblDescriptionWarning");

        txtProjectDescription.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtProjectDescription.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescriptionWarning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtProjectDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(txtProjectDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDescriptionWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 620, 110));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Título", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 18))); // NOI18N
        jPanel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        txtProjectTitle.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtProjectTitle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtProjectTitle.setPreferredSize(new java.awt.Dimension(30, 20));

        lblTitleWarning.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblTitleWarning.setForeground(new java.awt.Color(255, 0, 0));
        lblTitleWarning.setText("lblTitleWarning");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProjectTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitleWarning, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(txtProjectTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitleWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 110));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data de Início", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 18))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        calStartDate.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        calStartDate.setPreferredSize(new java.awt.Dimension(200, 22));

        lblStartDateWarning.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblStartDateWarning.setForeground(new java.awt.Color(255, 0, 0));
        lblStartDateWarning.setText("lblStartDateWarning");
        lblStartDateWarning.setMinimumSize(new java.awt.Dimension(209, 20));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStartDateWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStartDateWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 620, 110));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data de Fim", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 18))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        calEndDate.setPreferredSize(new java.awt.Dimension(200, 22));

        lblEndDateWarning.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblEndDateWarning.setForeground(new java.awt.Color(255, 0, 0));
        lblEndDateWarning.setText("lblEndDateWarning");
        lblEndDateWarning.setMinimumSize(new java.awt.Dimension(209, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEndDateWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(calEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEndDateWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 620, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCreateProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateProjectActionPerformed
        int p = s.getRepositoryProjects().addProject(s.getCurrentUser().getUserId(),
                txtProjectTitle.getText(), txtProjectDescription.getText(),
                calStartDate.getDate(), calEndDate.getDate(),
                s.getRepositoryUserProjectsAssociation());

        JOptionPane.showMessageDialog(null, "O projeto " + txtProjectTitle.getText() + " foi criado com sucesso!");

        this.dispose();

    }//GEN-LAST:event_btnCreateProjectActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CriarProjeto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CriarProjeto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CriarProjeto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CriarProjeto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                CriarProjeto2 dialog = new CriarProjeto2(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreateProject;
    private org.jdesktop.swingx.JXDatePicker calEndDate;
    private org.jdesktop.swingx.JXDatePicker calStartDate;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JLabel lblDescriptionWarning;
    private javax.swing.JLabel lblEndDateWarning;
    private javax.swing.JLabel lblStartDateWarning;
    private javax.swing.JLabel lblTitleWarning;
    private javax.swing.JTextField txtProjectDescription;
    private javax.swing.JTextField txtProjectTitle;
    // End of variables declaration//GEN-END:variables
}
