/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Backend.*;
import javax.swing.BorderFactory;

/**
 *
 * @author VarianInstaller
 */
public class DashBoard extends javax.swing.JDialog {

    Sistema s;

    /**
     * Creates new form DashBoard2
     */
    public DashBoard(java.awt.Frame parent, boolean modal, Sistema s) {
        super(parent, modal);
        initComponents();
        this.s = s;
        this.setTitle("DashBoard - " + s.getCurrentUser().getUserName() + " (" + s.getCurrentUser().getEmail() + ")");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStatistics = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuSignUpUser = new javax.swing.JMenuItem();
        menuChangeUserName = new javax.swing.JMenuItem();
        menuChangeEmail = new javax.swing.JMenuItem();
        menuChangePassword = new javax.swing.JMenuItem();
        menuAssignUsertoTask = new javax.swing.JMenuItem();
        menuAssociateUserToProject = new javax.swing.JMenuItem();
        menuDisplayUserRelationships = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuCreateProject = new javax.swing.JMenuItem();
        menuDisplayprojects = new javax.swing.JMenuItem();
        menuChangeProjectData = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuCreateTaskList = new javax.swing.JMenuItem();
        menuDisplayTaskList = new javax.swing.JMenuItem();
        menuEditTaskList = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuCreateTasks = new javax.swing.JMenuItem();
        menuDisplayTasks = new javax.swing.JMenuItem();
        menuEditTasks = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnStatistics.setText("Estatisticas");
        getContentPane().add(btnStatistics, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, -1, 40));

        jMenu1.setText("Ficheiro");

        menuExit.setText("Sair");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Utilizador");

        menuSignUpUser.setText("Registar");
        menuSignUpUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSignUpUserActionPerformed(evt);
            }
        });
        jMenu2.add(menuSignUpUser);

        menuChangeUserName.setText("Alterar Nome");
        menuChangeUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuChangeUserNameActionPerformed(evt);
            }
        });
        jMenu2.add(menuChangeUserName);

        menuChangeEmail.setText("Alterar Email");
        menuChangeEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuChangeEmailActionPerformed(evt);
            }
        });
        jMenu2.add(menuChangeEmail);

        menuChangePassword.setText("Alterar Password");
        menuChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuChangePasswordActionPerformed(evt);
            }
        });
        jMenu2.add(menuChangePassword);

        menuAssignUsertoTask.setText("Associar Utilizador a Tarefas");
        menuAssignUsertoTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAssignUsertoTaskActionPerformed(evt);
            }
        });
        jMenu2.add(menuAssignUsertoTask);

        menuAssociateUserToProject.setText("Associar Utilizador a Projetos");
        menuAssociateUserToProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAssociateUserToProjectActionPerformed(evt);
            }
        });
        jMenu2.add(menuAssociateUserToProject);

        menuDisplayUserRelationships.setText("Ver Relacionamentos");
        menuDisplayUserRelationships.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDisplayUserRelationshipsActionPerformed(evt);
            }
        });
        jMenu2.add(menuDisplayUserRelationships);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Projetos");

        menuCreateProject.setText("Criar Projeto");
        menuCreateProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCreateProjectActionPerformed(evt);
            }
        });
        jMenu3.add(menuCreateProject);

        menuDisplayprojects.setText("Mostrar Projectos");
        menuDisplayprojects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDisplayprojectsActionPerformed(evt);
            }
        });
        jMenu3.add(menuDisplayprojects);

        menuChangeProjectData.setText("Editar Dados de Projeto");
        menuChangeProjectData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuChangeProjectDataActionPerformed(evt);
            }
        });
        jMenu3.add(menuChangeProjectData);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Lista de Tarefas");

        menuCreateTaskList.setText("Criar Listas de Tarefa");
        menuCreateTaskList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCreateTaskListActionPerformed(evt);
            }
        });
        jMenu4.add(menuCreateTaskList);

        menuDisplayTaskList.setText("Mostrar Lista de Tarefas");
        jMenu4.add(menuDisplayTaskList);

        menuEditTaskList.setText("Editar Lista de Tarefas");
        jMenu4.add(menuEditTaskList);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Tarefas");

        menuCreateTasks.setText("Criar Tarefa");
        menuCreateTasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCreateTasksActionPerformed(evt);
            }
        });
        jMenu5.add(menuCreateTasks);

        menuDisplayTasks.setText("Mostrar Tarefas");
        menuDisplayTasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDisplayTasksActionPerformed(evt);
            }
        });
        jMenu5.add(menuDisplayTasks);

        menuEditTasks.setText("Editar Tarefas");
        menuEditTasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditTasksActionPerformed(evt);
            }
        });
        jMenu5.add(menuEditTasks);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void menuCreateProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCreateProjectActionPerformed

        CreateProject createProject = new CreateProject(null, true, s);
        createProject.setLocationRelativeTo(null);
        createProject.setVisible(true);

    }//GEN-LAST:event_menuCreateProjectActionPerformed

    private void menuChangeUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuChangeUserNameActionPerformed

        ChangeUserName changeUserName = new ChangeUserName(null, true, s);
        changeUserName.setLocationRelativeTo(null);
        changeUserName.setVisible(true);

        this.setTitle("DashBoard - " + s.getCurrentUser().getUserName() + " (" + s.getCurrentUser().getEmail() + ")");
    }//GEN-LAST:event_menuChangeUserNameActionPerformed

    private void menuChangeEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuChangeEmailActionPerformed
        ChangeUserEmail changeUserEmail = new ChangeUserEmail(null, true, s);
        changeUserEmail.setLocationRelativeTo(null);
        changeUserEmail.setVisible(true);
        this.setTitle("DashBoard - " + s.getCurrentUser().getUserName() + " (" + s.getCurrentUser().getEmail() + ")");
    }//GEN-LAST:event_menuChangeEmailActionPerformed

    private void menuChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuChangePasswordActionPerformed
        ChangeUserPassword changeUserPassword = new ChangeUserPassword(null, true, s);
        changeUserPassword.setLocationRelativeTo(null);
        changeUserPassword.setVisible(true);
    }//GEN-LAST:event_menuChangePasswordActionPerformed

    private void menuSignUpUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSignUpUserActionPerformed
        SignUpUser signUpUser = new SignUpUser(null, true, s);
        signUpUser.setLocationRelativeTo(null);
        signUpUser.setVisible(true);
    }//GEN-LAST:event_menuSignUpUserActionPerformed

    private void menuAssignUsertoTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAssignUsertoTaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAssignUsertoTaskActionPerformed

    private void menuDisplayUserRelationshipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDisplayUserRelationshipsActionPerformed
        DisplayUserRelationship displayUserRelationship = new DisplayUserRelationship(null, true, s);
        displayUserRelationship.setLocationRelativeTo(null);
        displayUserRelationship.setVisible(true);
    }//GEN-LAST:event_menuDisplayUserRelationshipsActionPerformed

    private void menuAssociateUserToProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAssociateUserToProjectActionPerformed
        AssociateUserToProjects associateUserToProject = new AssociateUserToProjects(null, true, s);
        associateUserToProject.setLocationRelativeTo(null);
        associateUserToProject.setVisible(true);
    }//GEN-LAST:event_menuAssociateUserToProjectActionPerformed

    private void menuCreateTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCreateTasksActionPerformed
        CreateTask ct = new CreateTask(null, true, s);
        ct.setLocationRelativeTo(null);
        ct.setVisible(true);
    }//GEN-LAST:event_menuCreateTasksActionPerformed

    private void menuDisplayTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDisplayTasksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuDisplayTasksActionPerformed

    private void menuEditTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditTasksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuEditTasksActionPerformed

    private void menuCreateTaskListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCreateTaskListActionPerformed
        CreateTaskLists createTaskList = new CreateTaskLists(null, true, s);
        createTaskList.setLocationRelativeTo(null);
        createTaskList.setVisible(true);
    }//GEN-LAST:event_menuCreateTaskListActionPerformed

    private void menuDisplayprojectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDisplayprojectsActionPerformed
        DisplayProjects displayProjects = new DisplayProjects(null, true, s);
        displayProjects.setLocationRelativeTo(null);
        displayProjects.setVisible(true);
    }//GEN-LAST:event_menuDisplayprojectsActionPerformed

    private void menuChangeProjectDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuChangeProjectDataActionPerformed
        ChangeProjectData changeProjectData = new ChangeProjectData(null, true, s);
        changeProjectData.setLocationRelativeTo(null);
        changeProjectData.setVisible(true);
    }//GEN-LAST:event_menuChangeProjectDataActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_menuExitActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStatistics;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAssignUsertoTask;
    private javax.swing.JMenuItem menuAssociateUserToProject;
    private javax.swing.JMenuItem menuChangeEmail;
    private javax.swing.JMenuItem menuChangePassword;
    private javax.swing.JMenuItem menuChangeProjectData;
    private javax.swing.JMenuItem menuChangeUserName;
    private javax.swing.JMenuItem menuCreateProject;
    private javax.swing.JMenuItem menuCreateTaskList;
    private javax.swing.JMenuItem menuCreateTasks;
    private javax.swing.JMenuItem menuDisplayTaskList;
    private javax.swing.JMenuItem menuDisplayTasks;
    private javax.swing.JMenuItem menuDisplayUserRelationships;
    private javax.swing.JMenuItem menuDisplayprojects;
    private javax.swing.JMenuItem menuEditTaskList;
    private javax.swing.JMenuItem menuEditTasks;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuSignUpUser;
    // End of variables declaration//GEN-END:variables
}
